services:
  node:
    image: nodeapp:1.0.0 # Usa l'immagine nodeapp:1.0.0 generata in precedenza
    container_name: node
    ports:
      - "8888:3000"
    volumes:
      - .\volumes\config.json:/usr/src/app/config.json
