version: '3.8'

services:
  node:
    build: . # Usa la immagine generata dal Dockerfile presente nella directory corrente
    container_name: node
    depends_on:
      - postgres
    ports:
      - "8888:3000"
  postgres:
    image: postgres:latest # Usa l'immagine postgres:latest di "docker hub"
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data